---
- name: Configure Elasticsearch.
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^script\.disable_dynamic', line: 'script.disable_dynamic: true' }
    - { regexp: 'network\.host', line: 'network.host: {{ elasticsearch_host }}' }
    - { regexp: 'http\.cors\.allow-origin', line: 'http.cors.allow-origin: {{ elasticsearch_cors_origin }}' }
  notify: restart elasticsearch